### ISSUE TITLE
Plugin has become worse since 0.1.9 update.

### ISSUE THREAD

**Issue by Valteur** [XertroV/tm-ghost-splits#1]
Since 0.1.9 update:

* After a solo session, I no longer see splits for all my runs anymore, only for my PB.
* Reference ghost is (often or always ?) displayed as +0.000 and with no color. It used to be green and show the checkpoint times.
* Spectating ghost no longer has color.
* On a campaign map with a lot of CPs, there was line wrap, and I couldn't expand the Ghost Splits window. (maybe not related to 0.1.9)

**Comment by XertroV** [comment]
thx for reporting.

As a (probably bad) workaround, you can uninstall Ghosts++ for the old behavior.

point 1 was intended since now it uses ghosts++ for ghosts if it can, but I'll add a way to get ghosts from MLFeed back too. 

points 2-4 aren't intended, will look into them.

**Comment by Valteur** [comment]
2 and 3 are fixed by changing the `is` comparisons in [these two lines](https://github.com/XertroV/tm-ghost-splits/blob/master/src/Main.as#L338-L339) by `AreGhostDupliates` comparisons.

![2024-08-11 17_05_29067903](https://github.com/user-attachments/assets/1322cebb-c3a3-466d-aa13-f49a7cf17ad4)

I'm investigating 4.

**Comment by XertroV** [comment]
Thanks for fixing @Valteur
